# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Introductory ML Course
author: ugniusalekna
baseurl: /intro-to-ml

execute:
  execute_notebooks: force

repository:
  url: https://github.com/ugniusalekna/intro-to-ml
  path_to_book: notebooks/
  branch: main

html:
  use_issues_button: true
  use_repository_button: true
