title: Introductory ML Course
author: ugniusalekna

execute:
  execute_notebooks: 'off'

launch_buttons:
  colab_url: https://colab.research.google.com

repository:
  url: https://github.com/ugniusalekna/intro-to-ml
  path_to_book: ""
  branch: main

parse:
  myst_extended_syntax: true
  myst_enable_extensions: 
    - amsmath

sphinx:
  config:
    templates_path: ["_templates"]
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    extensions:
      - jupyter_sphinx
      - sphinx_togglebutton
      - sphinx_copybutton
      - nbsphinx
      - sphinx.ext.mathjax
      - sphinx.ext.intersphinx
