title: Introductory ML Course
author: ugniusalekna

execute:
  execute_notebooks: 'off'

launch_buttons:
  binderhub_url: "https://mybinder.org"
  colab_url: https://colab.research.google.com
  thebe: true
  notebook_interface: "jupyterlab"

repository:
  url: https://github.com/ugniusalekna/intro-to-ml
  path_to_book: ""
  branch: main

parse:
  myst_extended_syntax: true
  myst_enable_extensions: 
    - amsmath

sphinx:
  config:
    templates_path: ["_templates"]
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    thebe_config:
      repository_url: "https://github.com/ugniusalekna/intro-to-ml"
      branch: "main"
      path_to_docs: "notebooks"