name: py311
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - scipy
  - ipykernel
  - notebook
  - dash=2.17.1
  - pillow
  - jupyterlab=4.2.4
  - pytorch
  - torchvision
  - pip:
      - jupyter-dash==0.4.2
      - plotly==5.23.0
